## How the training Works

* consider there is an input X, that should yield a positive answer 1.
* we want to tweak the weights w, such that w * x > 0
* we add the bias to x therefore x(n+1) = 1

### Notice: w is the same shape as x.

* consider swapping w to x ->  it will result in x*x 
* notice that x*x is a dot product and therefore be a positive number,
* x\*x = x(1 to n)\*x(1 to n) + x(n+1)\*x(n+1) >= x(n+1)\*x(n+1) = 1

hence if w = x on the next test it will score > 0 given the same x.

### We want to keep the changes
* we do not wish to completly override w.
* therefore we say w = w + X

notice that by the same reasoning w(new)\*x > w(old)\*x.


### Negative exmpales

* on the other hand consider X and y being negative,
* hence we want w * X < 0

####  Notice : 
* therefore consider -x * x would be a negative number.
* hence if we set w = w - x => w(new)\*x < w(old)\*x

thuse there is a better chance we will get a score less then 0 next try.


### Normalizing X
* another issue would be that not all inputs are equal
* the input \[1, 1\] will have 10% of the effect of the input \[10, 10\] on the weights.
* therefore we normalize, a.k.a we want the absolute sum of all cells in input to be exactly 1.


### Normalizing effect
* again notice that x.normalzie() * x > 0
* hence if we say w = w + x.normalized we will score better.

## Final algorithm :

>if y = 1 do:

>>   w = w + x.normalzied()

> else 

>>    w = w - x.normalzied()


In [78]:
import numpy as np
from neuron import Neuron

## Test on AND 

In [79]:
# A AND B or B and C
data = np.array([
    # A  B  C  O
    [0, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 1, 1, 1],
    [1, 0, 0, 0],
    [1, 0, 1, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 1],
])
data

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 1]])

In [80]:
x = data[:, :-1]
y = data[:, -1:]

print(x)
print(y)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]]


## Add bias to input

In [81]:
x_bias = np.ones((x.shape[0], 1))
x_train = np.c_[x, x_bias]
x_train

array([[0., 0., 0., 1.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 1.]])

## Create neuron and train
* we train by looping over all examples untill the neuron do not fails or we run more then 100 times.

In [82]:
n = Neuron(x_train, y)
n.weights

array([[0.],
       [0.],
       [0.],
       [0.]])

In [83]:
n = Neuron(x_train, y)

end_run = -1

for i in range(100):
    print("\n-------- run", i, "--------")
    err = 0
    done = True
    for j in range(x_train.shape[0]):
        pred = n.predict(x_train[j])
        actual = y[j]
        print("prediction :", pred, ", actual :", actual[0])
        change = n.train_one(x_train[j], actual)
        if change:
            err += 1
            done = False
    if done:
        end_run = i
        break
    else:
        print("End of run Num of Errors :", err)
        print("weights : ")
        print(n.weights)


-------- run 0 --------
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 1
prediction : 1 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 1
prediction : 1 , actual : 1
End of run Num of Errors : 3
weights : 
[[-0.16666667]
 [ 0.66666667]
 [ 0.33333333]
 [ 0.16666667]]

-------- run 1 --------
prediction : 1 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 1 , actual : 1
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 1
prediction : 1 , actual : 1
End of run Num of Errors : 2
weights : 
[[ 0.16666667]
 [ 1.        ]
 [ 0.33333333]
 [-0.5       ]]

-------- run 2 --------
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 1 , actual : 0
prediction : 0 , actual : 1
prediction : 0 , actual : 0
prediction : 1 , actual : 0
prediction : 0 , actual : 1
prediction : 1 , actual : 1
End of run Num of Errors : 4
weights : 
[[ 0.166666

In [84]:
print("\n------ training done ------")
print("training done on run :", end_run)
print("final weights :")
print(n.weights)


------ training done ------
training done on run : 7
final weights :
[[ 0.5       ]
 [ 1.33333333]
 [ 0.5       ]
 [-1.33333333]]
