## How the training Works

* consider there is an input X, that should yield a positive answer 1.
* we want to tweak the weights w, such that w * x > 0
* we add the bias to x therefore x(n+1) = 1

### Notice: w is the same shape as x.

* consider swapping w to x ->  it will result in x*x 
* notice that x*x is a dot product and therefore be a positive number,
* x\*x = x(1 to n)\*x(1 to n) + x(n+1)\*x(n+1) >= x(n+1)\*x(n+1) = 1

hence if w = x on the next test it will score > 0 given the same x.

### We want to keep the changes
* we do not wish to completly override w.
* therefore we say w = w + X

notice that by the same reasoning w(new)\*x > w(old)\*x.


### Negative exmpales

* on the other hand consider X and y being negative,
* hence we want w * X < 0

####  Notice : 
* therefore consider -x * x would be a negative number.
* hence if we set w = w - x => w(new)\*x < w(old)\*x

thuse there is a better chance we will get a score less then 0 next try.


### Normalizing X
* another issue would be that not all inputs are equal
* the input \[1, 1\] will have 10% of the effect of the input \[10, 10\] on the weights.
* therefore we normalize, a.k.a we want the absolute sum of all cells in input to be exactly 1.


### Normalizing effect
* again notice that x.normalzie() * x > 0
* hence if we say w = w + x.normalized we will score better.

## Final algorithm :

>if y = 1 do:

>>   w = w + x.normalzied()

> else 

>>    w = w - x.normalzied()


In [196]:
import numpy as np
from neuron import Neuron

## Test on AND 

In [197]:
# A AND B or B and C
data = np.array([
    # A  B  C  O
    [0, 0, 0, -1],
    [0, 0, 1, -1],
    [0, 1, 0, -1],
    [0, 1, 1, 1],
    [1, 0, 0, -1],
    [1, 0, 1, -1],
    [1, 1, 0, 1],
    [1, 1, 1, 1],
])
data.shape

(8, 4)

In [198]:
x = data[:, :-1]
y = data[:, -1:]

print(x)
print(y)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[-1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]


In [215]:
import neuron
importlib.reload(neuron)
from neuron import Neuron
n = Neuron(3, 1, 0.01)

n.predict(x)

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [207]:
print(n.weights)
n.train(x, y)
n.train(x, y)
n.train(x, y)

[[0.40166449]
 [1.45821983]
 [0.43616643]]


array([[1.42641461e-01, 3.49211938e-03, 1.16339003e+00, 2.34857712e-01,
        8.16190642e-04, 2.16543412e-01, 2.65375722e-01, 6.14234437e-03]])

In [208]:
n.predict(x)

array([[0., 0., 1., 1., 0., 0., 1., 1.]])

## Add bias to input

In [202]:
x_bias = np.ones((x.shape[0], 1))
x_train = np.c_[x, x_bias]
x_train

array([[0., 0., 0., 1.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 1.]])

## Create neuron and train
* we train by looping over all examples untill the neuron do not fails or we run more then 100 times.

In [203]:
n = Neuron(x.shape[1], 1)
n.weights

array([[0.],
       [0.],
       [0.]])

In [204]:
import importlib
import neuron
importlib.reload(neuron)
from neuron import Neuron
n = Neuron(3, 1)

#n.lsm_train(x_train[0], y[0])

print(x.shape)
print("x[3] :", x[3], ",y[3] :", y[3])
print("n.weights :", n.weights,  "predict x[3] :", [n.predict(x[3])])

# print(n.weights.flatten())
print("traing on x[3] err :", n.train(x[3], y[3]))


print("\nx[2] :", x[2], ",y[4] :", y[2])
print("n.weights :", n.weights.flatten(), n.bias,  "predict x[4] :", [n.predict(x[2])])

# print(n.weights.flatten())
print("traing on x[2] err :", n.train(x[2], y[2]))

print("\nn.weights :", n.weights.flatten(), n.bias,  "predict x[3] :", [n.predict(x[3])])
print("traing on x[2] err :", n.train(x[2], y[2]))
print("\nn.weights :", n.weights.flatten(), n.bias,  "predict x[2] :", [n.predict(x[2])])


(8, 3)
x[3] : [0 1 1] ,y[3] : [1]
n.weights : [[0.]
 [0.]
 [0.]] predict x[3] : [array([[0.]])]
traing on x[3] err : [[1.]]

x[2] : [0 1 0] ,y[4] : [-1]
n.weights : [0.  0.2 0.2] [[0.2]] predict x[4] : [array([[1.]])]
traing on x[2] err : [[1.96]]

n.weights : [ 0.   -0.08  0.2 ] [[-0.08]] predict x[3] : [array([[1.]])]
traing on x[2] err : [[0.7056]]

n.weights : [ 0.    -0.248  0.2  ] [[-0.248]] predict x[2] : [array([[0.]])]


In [205]:
import random
from neuron import Neuron
importlib.reload(neuron)
n = Neuron(3, 1, 0.01)


def train(size : int):
    train_err = 0
    for i in range(size):
        j = random.randint(0, x.shape[0]-1)
        train_err += n.train(x[j], y[j])
    print("train err :", train_err)
    # print("weights :")
    # print(n.weights)


for i in range(10):
    print("------ batch :", i, "------")
    train(100)


for i in range(0, x.shape[0]):
    print("predicted : ", n.predict(x[i]), " actual :", y[i])
print("\nn.weights :", n.weights.flatten(), n.bias,  "predict x[2] :", [n.predict(x[2])])

------ batch : 0 ------
train err : [[82.78776443]]
------ batch : 1 ------
train err : [[63.0616138]]
------ batch : 2 ------
train err : [[43.75478797]]
------ batch : 3 ------
train err : [[27.75964946]]
------ batch : 4 ------
train err : [[36.11541217]]
------ batch : 5 ------
train err : [[20.32264533]]
------ batch : 6 ------
train err : [[32.19777247]]
------ batch : 7 ------
train err : [[28.27411542]]
------ batch : 8 ------
train err : [[23.80269643]]
------ batch : 9 ------
train err : [[19.41953482]]
predicted :  [[0.]]  actual : [-1]
predicted :  [[0.]]  actual : [-1]
predicted :  [[1.]]  actual : [-1]
predicted :  [[1.]]  actual : [1]
predicted :  [[0.]]  actual : [-1]
predicted :  [[0.]]  actual : [-1]
predicted :  [[1.]]  actual : [1]
predicted :  [[1.]]  actual : [1]

n.weights : [0.40166449 1.45821983 0.43616643] [[-1.3635599]] predict x[2] : [array([[1.]])]


In [206]:
print("\n------ training done ------")
print("training done on run :", 1)
print("final weights :")
print(n.weights)


------ training done ------
training done on run : 1
final weights :
[[0.40166449]
 [1.45821983]
 [0.43616643]]
