<center>
<h1> Test my neural network class computation</h1>
<h2> Part C&D </h2>
<h3> By : Michael trushkin </h3>
</center>


## for an assignment i have implemented a neural network, and back propogation algorithm.
* in this short notebook, iam testing if the neural network indeed working.


In [166]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import myGraphicFuncs
import NeuralNet
importlib.reload(myGraphicFuncs)
importlib.reload(NeuralNet)
from NeuralNet import NeuralNetwork
np.set_printoptions(suppress=True)

### initialize neural network with 3 inputs, 4 neurons in hidden layer, and 2 outputs.
* print weights,
* print biases

In [167]:
nt = NeuralNetwork([3, 4, 2])
print("weights 3x4 :\n",nt.weights[0])
print("weights 4x2 :\n",nt.weights[1])
print("biases 4x1 :\n",nt.biases[0])
print("biases 2x1 :\n",nt.biases[1])

weights 3x4 :
 [[0.28066152 0.18695719 0.14694134 0.7147724 ]
 [0.66461753 0.25210609 0.75350868 0.4729776 ]
 [0.01735562 0.53093339 0.49151849 0.36204476]]
weights 4x2 :
 [[0.97349594 0.14886551]
 [0.42805368 0.4879479 ]
 [0.7736002  0.20975695]
 [0.79411858 0.32604069]]
biases 4x1 :
 [[0.09907117]
 [0.89998453]
 [0.96217204]
 [0.9778831 ]]
biases 2x1 :
 [[0.21784695]
 [0.28799016]]


## Test neural netowrk with 1 input

In [168]:
data = np.array([0,1,0, 0.5, 0]) # 3 inputs 2 outputs
nt = NeuralNetwork([3, 3, 2])
x = data[:-2]
y = data[-2:]
print("prediction initial :\n", nt.predict(x))

for i in range(5):
    err = 0
    for j in range(100):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)

prediction initial :
 [[0.90142696 0.79378017]]
iter 99 , error : 41.96390902866582 
 [[0.79686037 0.28961779]] actual :
 [0.5 0. ]
iter 99 , error : 9.521260039492798 
 [[0.6314292  0.16475657]] actual :
 [0.5 0. ]
iter 99 , error : 2.68275429949481 
 [[0.54014371 0.12192983]] actual :
 [0.5 0. ]
iter 99 , error : 1.2735269260914122 
 [[0.51130405 0.09982257]] actual :
 [0.5 0. ]
iter 99 , error : 0.8625618993156123 
 [[0.50306212 0.08605367]] actual :
 [0.5 0. ]


### we can clearly see the network is able to "learn" this simply data example, and we can even pass 1d arrays of inputs

## Create few data examples, and train on all of them.

In [169]:
nt = NeuralNetwork([3, 7, 2])
print(nt.layers)
data = np.array([[1,1,1, 0,0],
                 [0,0,0, 1,1],
                 [0,0,1, 1,0],
                 [1,1,0, 0,1],
                 [1,0,1, 0.5,0]])
x = data[:,:-2]
y = data[:,-2:]
print(x) # the X of the input
print(y) # the Y of the input

[3, 7, 2]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]


In [170]:
nt.predict(x)

array([[0.97618193, 0.99025907],
       [0.94550473, 0.97705121],
       [0.95999834, 0.98342018],
       [0.97179757, 0.98843741],
       [0.97037406, 0.98757549]])

In [171]:
nt.train(x, y)

5.04683728714332

In [172]:
nt.predict(x)

array([[0.97539866, 0.9900647 ],
       [0.94421649, 0.97671814],
       [0.95889857, 0.98314032],
       [0.97092383, 0.98821975],
       [0.96946648, 0.9873429 ]])

In [175]:
nt = NeuralNetwork([3, 4, 2])
print("initial :\n", nt.predict(x))
for j in range(10):
    err = 0
    for i in range(350):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)

initial :
 [[0.94973707 0.88132882]
 [0.91211979 0.81302445]
 [0.92998215 0.84734389]
 [0.9411416  0.86245075]
 [0.94453568 0.87382355]]
iter 0 , error : 718.0713109991555 
 [[0.44949063 0.31383304]
 [0.50463566 0.57630913]
 [0.49452306 0.30108884]
 [0.44121929 0.57458893]
 [0.46065636 0.27207947]] actual :
 [[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]
iter 1 , error : 400.3214172437168 
 [[0.46608342 0.19865914]
 [0.48226232 0.72489062]
 [0.61407336 0.12920754]
 [0.30911953 0.88552031]
 [0.52905647 0.11934067]] actual :
 [[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]
iter 2 , error : 221.12603229442897 
 [[0.24978038 0.20458426]
 [0.6414909  0.76248694]
 [0.81750018 0.08626526]
 [0.20810875 0.91421344]
 [0.55193796 0.09323292]] actual :
 [[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]
iter 3 , error : 97.3906001432143 
 [[0.14591721 0.16296709]
 [0.75568553 0.81280231]
 [0.90341756 0.07496107]
 [0.17055436 0.91318212]
 [0.51493875 0.08383854]] actual :
 [[0

## Network learns quite nicely!

## try bigger networks, with more layers

In [174]:
nt = NeuralNetwork([3, 4, 5, 2])
print("initial :\n", nt.predict(x))
for j in range(10):
    err = 0
    for i in range(1000):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)

initial :
 [[0.92968717 0.93178467]
 [0.92009697 0.92295561]
 [0.92642525 0.92863629]
 [0.92613716 0.92863423]
 [0.92807378 0.93034139]]
iter 0 , error : 2193.6444938801296 
 [[0.48689215 0.37663099]
 [0.50992802 0.4312748 ]
 [0.49380694 0.38629581]
 [0.49716804 0.41301014]
 [0.48961628 0.38087267]] actual :
 [[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]
iter 1 , error : 1655.423864723586 
 [[0.52003    0.2952479 ]
 [0.50740313 0.54535281]
 [0.65015383 0.15039178]
 [0.25323313 0.92944331]
 [0.58770186 0.20331241]] actual :
 [[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]
iter 2 , error : 795.0908862447266 
 [[0.37604735 0.21725684]
 [0.51687808 0.76713119]
 [0.83758789 0.02514083]
 [0.20902385 0.98869172]
 [0.5697577  0.08354431]] actual :
 [[0.  0. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]]
iter 3 , error : 239.38078688107234 
 [[0.08585343 0.09487638]
 [0.88635331 0.91003561]
 [0.91640269 0.01048855]
 [0.09259238 0.97697318]
 [0.52219468 0.02365506]] actual :
 [