<center>
<h1> Test my neural network class computation</h1>
<h2> Part C&D </h2>
<h3> By : Michael trushkin </h3>
</center>


## for an assignment i have implemented a neural network, and back propogation algorithm.
* in this short notebook, iam testing if the neural network indeed working.


In [578]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import myGraphicFuncs
import NeuralNet
importlib.reload(myGraphicFuncs)
importlib.reload(NeuralNet)
from NeuralNet import NeuralNetwork
np.set_printoptions(suppress=True)

### initialize neural network with 3 inputs, 4 neurons in hidden layer, and 2 outputs.
* print weights,
* print biases

In [579]:
nt = NeuralNetwork([3, 4, 2])
print("weights 3x4 :\n",nt.weights[0])
print("weights 4x2 :\n",nt.weights[1])
print("biases 4x1 :\n",nt.biases[0])
print("biases 2x1 :\n",nt.biases[1])

weights 3x4 :
 [[0.19356739 0.62177866 0.86186532 0.57866102]
 [0.70619265 0.60460777 0.47366681 0.98549703]
 [0.69552854 0.45745475 0.44951906 0.33113239]]
weights 4x2 :
 [[0.57674137 0.61969969]
 [0.13381523 0.71366484]
 [0.51609857 0.06306703]
 [0.69427447 0.87007734]]
biases 4x1 :
 [[0.66154142]
 [0.42424129]
 [0.12094988]
 [0.51673855]]
biases 2x1 :
 [[0.99130023]
 [0.72999609]]


## Test neural netowrk with 1 input

In [580]:
data = np.array([0,1,0, 0.5, 0]) # 3 inputs 2 outputs
nt = NeuralNetwork([3, 3, 2])
x = data[:-2]
y = data[-2:]
print("prediction initial :\n", nt.predict(x))

for i in range(5):
    err = 0
    for j in range(100):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)

prediction initial :
 [[0.71402796 0.87766754]]
iter 99 , error : 11.935659965235656 
 [[0.5003246  0.08258151]] actual :
 [0.5 0. ]
iter 99 , error : 0.4322643746608055 
 [[0.50007712 0.05348089]] actual :
 [0.5 0. ]
iter 99 , error : 0.2242175346661142 
 [[0.50004766 0.04216467]] actual :
 [0.5 0. ]
iter 99 , error : 0.15055696747372502 
 [[0.5000343  0.03578833]] actual :
 [0.5 0. ]
iter 99 , error : 0.11289966972108753 
 [[0.5000267  0.03157981]] actual :
 [0.5 0. ]


### we can clearly see the network is able to "learn" this simply data example, and we can even pass 1d arrays of inputs

## Create few data examples, and train on all of them.

In [581]:
nt = NeuralNetwork([3, 7, 2])
print(nt.layers)
data = np.array([[0,0,0, 0,0],
                 [0,0,1, 1,0],
                 [0,1,0, 1,0],
                 [0,1,1, 0,1],
                 [1,0,0, 1,0],
                 [1,0,1, 0,1],
                 [1,1,0, 0,1],
                 [1,1,1, 0,0]])
x = data[:,:-2]
y = data[:,-2:]
print(x) # the X of the input
print(y) # the Y of the input

[3, 7, 2]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]


In [582]:
nt.predict(x)

array([[0.9290904 , 0.86067738],
       [0.95339951, 0.89554602],
       [0.9479123 , 0.88610081],
       [0.962685  , 0.91159972],
       [0.95039703, 0.89866945],
       [0.96417611, 0.91957347],
       [0.96020332, 0.91360152],
       [0.96897965, 0.92851107]])

In [583]:
nt.train(x, y)

1.0759117841435581

In [584]:
nt.predict(x)

array([[0.92484725, 0.84487881],
       [0.95008533, 0.8811687 ],
       [0.94435116, 0.87114977],
       [0.95981646, 0.89827539],
       [0.94691821, 0.88484129],
       [0.96137601, 0.90714493],
       [0.95718216, 0.90070918],
       [0.96644715, 0.91687604]])

In [585]:
nt = NeuralNetwork([3, 8, 4, 2])
print("biases :\n",nt.biases)
print(x)
print("initial :\n", nt.predict(x),"\n---------------------------")
for j in range(10):
    err = 0
    for i in range(5000):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)
    print("alpha",nt.alpha,"\n")
    #print(nt.err1000)
nt.biases

biases :
 {0: array([[0.1699611 ],
       [0.49920787],
       [0.33182365],
       [0.28940972],
       [0.47058578],
       [0.45053038],
       [0.02863732],
       [0.63535063]]), 1: array([[0.89651365],
       [0.68926922],
       [0.40554741],
       [0.77241704]]), 2: array([[0.59170572],
       [0.25125604]])}
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
initial :
 [[0.8727518  0.83662317]
 [0.87387822 0.83837316]
 [0.87490562 0.83996276]
 [0.87546096 0.84087282]
 [0.8746665  0.83952027]
 [0.87534419 0.84064105]
 [0.87590881 0.84157096]
 [0.87624808 0.84215291]] 
---------------------------
iter 0 , error : 1346.0599790821163 
 [[0.11672085 0.04447561]
 [0.91586954 0.02123397]
 [0.92204545 0.01989256]
 [0.0419652  0.74711304]
 [0.92640771 0.01921237]
 [0.04214368 0.7447517 ]
 [0.0423001  0.74136903]
 [0.04190414 0.73354703]] actual :
 [[0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
alpha 0.35355339059327373 

iter 1 , error : 113.81157052481

{0: array([[-4.80155005],
        [-4.77428033],
        [-2.27695396],
        [-2.79360445],
        [ 3.68657041],
        [-0.84879704],
        [-0.69699   ],
        [-2.01513661]]),
 1: array([[ 1.3048747 ],
        [-5.86156646],
        [-2.82620858],
        [-1.15206955]]),
 2: array([[-2.41772299],
        [-2.4838808 ]])}

## Network learns quite nicely!

## try bigger networks, with more layers

In [588]:
nt = NeuralNetwork([3, 4, 5, 2])
print("initial :\n", nt.predict(x))
for j in range(10):
    err = 0
    for i in range(2000):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)

initial :
 [[0.92329706 0.96182032]
 [0.92652773 0.96453606]
 [0.92623401 0.96438126]
 [0.92838279 0.96613612]
 [0.92712154 0.96494904]
 [0.92887489 0.96642978]
 [0.92878627 0.9664102 ]
 [0.92988572 0.9673119 ]]
iter 0 , error : 780.4616727192322 
 [[0.82185591 0.04054309]
 [0.76222407 0.05743232]
 [0.75936142 0.05862059]
 [0.06319729 0.75472548]
 [0.76472548 0.05657581]
 [0.06557109 0.74639581]
 [0.0647537  0.74956177]
 [0.05023761 0.79690346]] actual :
 [[0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
iter 1 , error : 245.63107854908208 
 [[0.16515914 0.11539503]
 [0.88329277 0.00330087]
 [0.88427456 0.00331928]
 [0.00201049 0.90839421]
 [0.89423675 0.00296533]
 [0.00202089 0.90684365]
 [0.00205236 0.90747225]
 [0.10618185 0.14192892]] actual :
 [[0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
iter 2 , error : 15.092874321892804 
 [[0.07174639 0.05838729]
 [0.94382177 0.00039033]
 [0.94565343 0.00038301]
 [0.00014293 0.9571672 ]
 [0.95264985 0.00032824]
 [0.00015052 0

In [587]:
nt = NeuralNetwork([3, 4, 5, 2], momentum=0)
print("initial :\n", nt.predict(x))
for j in range(10):
    err = 0
    for i in range(2000):
        err += nt.train(x, y)
    print("iter", j, ", error :", err ,"\n",nt.predict(x), "actual :\n", y)

initial :
 [[0.89820325 0.95597228]
 [0.90170733 0.95813913]
 [0.90190376 0.95816138]
 [0.9038706  0.95945844]
 [0.90092735 0.95753167]
 [0.90334453 0.95911258]
 [0.90342468 0.95905984]
 [0.90478135 0.96002207]]
iter 0 , error : 943.4567627243314 
 [[0.38096169 0.37587091]
 [0.37490405 0.37816215]
 [0.37488746 0.37779091]
 [0.37064439 0.37918861]
 [0.37690299 0.37719183]
 [0.37184586 0.37888024]
 [0.37212509 0.37856642]
 [0.36863787 0.37958333]] actual :
 [[0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
iter 1 , error : 924.719181558454 
 [[0.42726926 0.33674393]
 [0.38233208 0.38139473]
 [0.38530949 0.37733239]
 [0.35384175 0.41032263]
 [0.39570729 0.36681418]
 [0.35977488 0.40400563]
 [0.36249353 0.40057634]
 [0.34083281 0.42358303]] actual :
 [[0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
iter 2 , error : 633.7747086359963 
 [[0.89573187 0.02976389]
 [0.80112324 0.06101543]
 [0.80286756 0.06010048]
 [0.07105893 0.7687072 ]
 [0.80181937 0.06037803]
 [0.07083001 0.76

In [ ]:
# for j in range(50):
#     err = 0
#     for k in range(250):
#         permutation = np.random.permutation(1000)
#         for i in range(10):
#             d = permutation[i*32:(i+1)*32]
#             err += net_t2.train(x[d, :], y[d, :])
#     print(j, err, net_t2.alpha)
# print(net_t2.predict(x[:10, :]))
# print(net_t2.predict(x[-10:, :]))